In [4]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\acer\OneDrive\Attachments\day-12-cleaned.csv")

In [6]:
df.shape

(9994, 9)

In [7]:
df.head()

,Order ID,Customer ID,Postal Code,Sales,Product ID,Quantity,Discount,Profit,Order Date
0,CA-2016-152156,CG-12520,42420,731.94,FUR-CH-10000454,3,0.0,? 219.582,11-Aug-16
1,CA-2015-106320,EB-13870,84057,1044.63,FUR-TA-10000577,3,0.0,? 240.2649,25-Sep-15
2,CA-2016-121755,EH-13945,90049,90.57,TEC-AC-10003027,3,0.0,? 11.7741,16-Jan-16
3,CA-2016-169194,LH-16900,19901,45.00,TEC-AC-10002167,3,0.0,? 4.95,20-Jun-16
4,CA-2015-135545,KM-16720,90004,146.73,OFF-PA-10003892,3,0.0,? 68.9631,24-Nov-15

In [8]:
df.tail()

,Order ID,Customer ID,Postal Code,Sales,Product ID,Quantity,Discount,Profit,Order Date
9989,CA-2016-105781,JF-15565,10024,326.6460,FUR-CH-10001802,3,0.10,? 39.9234,16-Feb-16
9990,CA-2017-144491,CJ-12010,77070,1023.3320,FUR-BO-10001811,5,0.32,30.098 -?,27-Mar-17
9991,CA-2016-122581,JK-15370,10035,573.1740,FUR-CH-10002961,7,0.10,? 63.686,21-Aug-16
9992,CA-2015-104948,KH-16510,92404,683.3320,FUR-BO-10004357,4,0.15,40.196 -?,13-Nov-15
9993,CA-2015-168088,CM-12655,77041,383.4656,FUR-BO-10004218,4,0.32,67.6704 -?,19-Mar-15

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Customer ID  9994 non-null   object
 2   Postal Code  9994 non-null   int64
 3   Sales        9994 non-null   float64
 4   Product ID   9994 non-null   object
 5   Quantity     9994 non-null   int64
 6   Discount     9994 non-null   float64
 7   Profit       9994 non-null   object
 8   Order Date   9994 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 702.8+ KB

In [10]:
df.describe()

        Postal Code         Sales     Quantity     Discount
count   9994.000000   9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203
std    32063.693350    623.245101     2.225110     0.206452
min     1040.000000      0.444000     1.000000     0.000000
25%    23223.000000     17.280000     2.000000     0.000000
50%    56430.500000     54.490000     3.000000     0.200000
75%    90008.000000    209.940000     5.000000     0.200000
max    99301.000000  22638.480000    14.000000     0.800000

In [11]:
#How many rows
df.shape[0]

9994

In [12]:
#How many columns
df.shape[1]

9

In [14]:
#Which columns have missing value
df.isnull().sum()

Order ID       0
Customer ID    0
Postal Code    0
Sales          0
Product ID     0
Quantity       0
Discount       0
Profit         0
Order Date     0
dtype: int64